services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: smartflow
      POSTGRES_PASSWORD: smartflow
      POSTGRES_DB: smartflow
    ports:
      - "5432:5432"
    volumes:
      - smartflow_pgdata:/var/lib/postgresql/data

volumes:
  smartflow_pgdata: